name: VSCode Extension
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
        working-directory: stylua-vscode
      - name: Run ESLint
        run: npm run lint
        working-directory: stylua-vscode
      - name: Prettier
        run: npm run check:format
        working-directory: stylua-vscode

  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
      - run: npm install
        working-directory: stylua-vscode
      - run: xvfb-run -a npm test
        working-directory: stylua-vscode
        if: runner.os == 'Linux'
      - run: npm test
        working-directory: stylua-vscode
        if: runner.os != 'Linux'
