name: Extension Release

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  extension-release:
    name: Release Extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - run: npm ci
        working-directory: stylua-vscode

      - name: Publish VSCode Extension
        working-directory: stylua-vscode
        run: npx vsce publish --pat ${{ secrets.MARKETPLACE_TOKEN }}

      - name: Publish OpenVSX Extension
        working-directory: stylua-vscode
        run: npx ovsx publish --pat ${{ secrets.OVSX_TOKEN }}
