name: Packaging Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  # Ensure it builds on all platforms
  npm_smoketest:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
      - name: Attempt install
        run: npm install --package-locked
        working-directory: stylua-npm-bin
      - name: Attempt run
        run: npx . --version
        working-directory: stylua-npm-bin
  pip_smoketest:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v6
      - name: Attempt install
        run: pip install .
