name: Release

on:
  push:
    tags: ["*"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    needs: []
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact-name: stylua-windows-x86_64
            cargo-target: x86_64-pc-windows-msvc
          - os: ubuntu-22.04
            artifact-name: stylua-linux-x86_64
            cargo-target: x86_64-unknown-linux-gnu
          - os: ubuntu-22.04
            artifact-name: stylua-linux-x86_64-musl
            cargo-target: x86_64-unknown-linux-musl
          - os: ubuntu-22.04-arm
            artifact-name: stylua-linux-aarch64
            cargo-target: aarch64-unknown-linux-gnu
          - os: ubuntu-22.04-arm
            artifact-name: stylua-linux-aarch64-musl
            cargo-target: aarch64-unknown-linux-musl
          - os: macos-latest
            artifact-name: stylua-macos-x86_64
            cargo-target: x86_64-apple-darwin
          - os: macos-latest
            artifact-name: stylua-macos-aarch64
            cargo-target: aarch64-apple-darwin

    name: Build (${{ matrix.artifact-name }})
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # stable
        with:
          toolchain: stable
          target: ${{ matrix.cargo-target }}

      - name: Build Binary (All features)
        run: cargo build --verbose --locked --release --features lua52,lua53,lua54,luau,luajit,cfxlua --target ${{ matrix.cargo-target }}
        env:
          CARGO_TARGET_DIR: output

      - name: Setup Archive + Extension
        shell: bash
        run: |
          mkdir -p staging

          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp "output/${{ matrix.cargo-target }}/release/stylua.exe" staging/
            cd staging
            7z a ../release.zip *
          else
            cp "output/${{ matrix.cargo-target }}/release/stylua" staging/
            cd staging
            zip ../release.zip *
          fi

          mv release.zip "${{ matrix.artifact-name }}.zip"

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ matrix.artifact-name }}.zip

      - name: Upload Binary to Release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2
        with:
          draft: true
          files: ${{ matrix.artifact-name }}.zip

  release_cargo:
    name: Publish to cargo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # stable
        with:
          toolchain: stable

      - name: Publish to cargo
        run: cargo publish --verbose --locked --token ${{ secrets.CARGO_TOKEN }}

  release_npm_wasm:
    name: Publish wasm to npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # stable
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"

      - name: Build WASM
        run: |
          chmod u+x ./wasm/build-wasm.sh
          ./wasm/build-wasm.sh

      - name: Publish to npm
        working-directory: wasm
        run: npm publish

  release_npm_bin:
    name: Publish binary to npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"

      - name: Setup README and LICENSE
        run: |
          cp README.md stylua-npm-bin/
          cp LICENSE.md stylua-npm-bin/

      - name: Publish to npm
        working-directory: stylua-npm-bin
        run: npm publish

  release_docker:
    name: Publish image to container registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3
        id: buildx
        with:
          install: true

      - uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        id: meta
        env:
          DOCKER_METADATA_PR_HEAD_SHA: "true"
        with:
          images: johnnymorganz/stylua
          tags: |
            type=semver,pattern={{version}}
            type=sha

      - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: .
          file: Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha
