name: Pull Latest Test Cases
on:
  workflow_dispatch:
  schedule:
    - cron: "10 0 * * *" # Runs at 00:10 UTC every day

permissions:
  contents: read

jobs:
  retrieve_cases:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Pull latest tests
        run: python ./.github/retrieve_test_cases.py

      - name: Update insta snapshots
        run: |
          cargo install cargo-insta
          CI=false cargo insta test --accept
          CI=false cargo insta test --features lua52 --accept
          CI=false cargo insta test --features lua53 --accept
          CI=false cargo insta test --features lua54 --accept
          CI=false cargo insta test --features luau --accept
          CI=false cargo insta test --features cfxlua --accept

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@4e1beaa7521e8b457b572c090b25bd3db56bf1c5 # v5
        with:
          title: Update external test cases
          body: |
            Pulls in new changes from external repositories for test cases
            - This pull request is **auto-generated**
          branch: auto/update-external-test-cases
          commit-message: Update external test cases
          base: main
